### ISSUE TITLE
composer install

### ISSUE THREAD

**Issue by truemoroz** [deemru/WavesKit#11]
I installed with `composer require deemru/waveskit`
And what I get you can see [here](https://yadi.sk/d/rpGtat6i-3WuxA)
I think you need to update package

**Comment by deemru** [comment]
> I think you need to update package

Why? This package is fully tested in php environments from 5.6 to 7.3 on every commit: https://travis-ci.org/deemru/WavesKit/builds

It looks like something wrong with your particular php environment.

Try: `composer clear-cache && composer update`

If it would not help, please provide your `composer.json` amd `composer.lock` files and steps to reproduce the issue.

**Comment by deemru** [comment]
Cannot reproduce.
