### ISSUE TITLE
Update Asset Info Transaction

### ISSUE THREAD

**Issue by LuisaFraub** [deemru/WavesKit#14]
Hi, I would like to use the "Update Asset Info Transaction", but when I've tried to compile an asset script with a restriction on it, I've got an error even if the script was correct in waves-ide.com.
Basically I think that it depends on version: is it possible to have this transaction using your library? In the documentation I have not seen this kind of functionality, but... better ask!

Thanks in advance.

**Comment by deemru** [comment]
From your description i do not see any issues regarding WavesKit.

Update Asset Info Transaction can update only [`name` and `description` of an asset](https://docs.waves.tech/en/blockchain/transaction-type/update-asset-info-transaction).

If you want to issue a token -- use [`txIssue()`](https://github.com/deemru/WavesKit/blob/e85d727049d2738601cbde9cd894538a26d9ec0c/docs/WavesKit.md#waveskittxissue).

Why do you want to use Update Asset Info Transaction?

**Comment by LuisaFraub** [comment]
You're right, this is not an issue with WavesKit, just a question... 

I'm using WavesKit in several ways and one of these is txIssue() to create an NFT.
After the issue, I would like to make possible the update of NFT description. Is this possible using WavesKit? How?

**Comment by deemru** [comment]
Not implemented, but will be soon

**Comment by LuisaFraub** [comment]
Great! Thank you 👍

**Comment by deemru** [comment]
https://github.com/deemru/WavesKit/releases/tag/1.0.21
