### ISSUE TITLE
Cannot declare class kornrunner\Keccak, because the name is already in use

### ISSUE THREAD

**Issue by vpsitua** [deemru/WavesKit#17]
Добрый день!
У меня уже подключена support/Keccak.php отдельным пакетом. Вы не сменили namespace в переопределенном классе Keccak.php и теперь возникают ошибкa `Cannot declare class kornrunner\Keccak, because the name is already in use`

**Comment by deemru** [comment]
Да, косячно, надо бы исправить.

**Comment by vpsitua** [comment]
Круто, спасибо! А могли бы еще изменить tag 1.0.34 => 1.0.35

**Comment by deemru** [comment]
Да, ждал тестов, прошли успешно, будет новый tag.
