### ISSUE TITLE
txInvokeScript return false

### ISSUE THREAD

**Issue by LuisaFraub** [deemru/WavesKit#6]
Hi, I'm using the latest version of the WavesKit, txInvokeScript function in particular.
	$wk = new WavesKit( 'T' );	//  'T' for testnet
	$wk->setSeed( $user_bc_seed );
	$options =  array(
		"fee" => 900000
	);
	$args = [
		$titolo,
		$arrayData
	];
	$tx = $wk->txSign( $tx );
	$tx = $wk->txInvokeScript( $user_bc_address, "addItem", $args, null, $options);
	$tx = $wk->txBroadcast( $tx );
	$response = json_encode($tx);

$tx before txBroadcast look like 
{
	"type":16,
	"version":1,
	"sender":"3MsJAaF5QnFSPWt1FbTYg2rZEYGE89zL9xm",
	"senderPublicKey":"AuwNnJne9DDzFJMVzgSTvELEvJKcS6sAwa1pYot7NSZc",
	"timestamp":1565976714741,
	"dApp":"3MsJAaF5QnFSPWt1FbTYg2rZEYGE89zL9xm",
	"call":{
		"function":"addItem",
		"args":[
			{"type":"string","value":"eee"},
			{"type":"string","value":"{\"titolo\":\"eee\",\"descrizione\":\"ytutyuty\",\"allegato\":\"\"}"}]
	},
	"payment":[],
	"fee":500000,
	"chainId":84
}

The function addItem is a script deployed into dApp and works if called from Waves IDE.
From my php code, I get FALSE as answer but I can't understand what happens.

Someone can help me? Thank in advance

**Comment by deemru** [comment]
Thanks for the report, it is fixed: https://github.com/deemru/WavesKit/commit/bc10e6ab852291546e14a673760c4e1f8e29ca17

Just use `composer update`.

**Comment by LuisaFraub** [comment]
I tried with the fix, but nothing has change: may I try something else?
