### ISSUE TITLE
Request: Add method to get Data by providing a regexp

### ISSUE THREAD

**Issue by sunchaser68** [deemru/WavesKit#8]
Proposal to add a method to retrieve Data by specifying a regexp. The engine should extract all keys satisfying a certain regexp. 

There could be a performance problem if the regexp expression extract too many items, maybe a limit can be added.

Alternatively please evaluate an API to extract all data from an address so it can be processed in an array

**Comment by deemru** [comment]
Actually you can already use `fetch()` for your custom requests:
```php
define( 'WK_CURL_TIMEOUT', 30 ); // 30 seconds request timeout instead of 5 seconds by default

$wk = new WavesKit();
$data = $wk->fetch( '/addresses/data/3P8M8XGF2uzDazV5fzdKNxrbC3YqCWScKxw?matches=[$].*' );
$records = $wk->json_decode( $data );
foreach( $records as $record )
    $wk->log( 'i', json_encode( $record ) );
```

Currently there is no plan to implement more for that.

**Comment by sunchaser68** [comment]
Thank you deemru
